### ISSUE TITLE
how to search?

### ISSUE THREAD

**Issue by yu2chuan** [sharvenp/md.it#1]
I've tried the version 1.1.1. But I cannot find the feature search. Let me know how to do a search or you can add this feature to search a term in a folder with a lot of md files.

**Comment by sharvenp** [comment]
Sorry this was not mentioned in the readme documentation, but to search a term within a file you can do `ctrl`+`f` which will open a search toolbar at the bottom of the editor. This feature can also be used for find and replace.

I will keep this issue open for adding a feature that allows a term to be searched in a folder of md files.

**Comment by sharvenp** [comment]
Searching text within a md file is already supported. However searching a term within a folder of md files is out of scope and would go against the simplicity of md.it. Hence this feature will not be implemented.

Alternatively, #12 suggests a new feature that will allow the user to open a folder of md files and access them in md.it.
